### ISSUE TITLE
Alias/facade not working

### ISSUE THREAD

**Issue by ryancwalsh** [hackerESQ/laravel-settings#3]
Thanks for sharing your repo.  It looks exciting.

I have a question about it.

Even though I'm running Laravel 5.7, your alias/facade doesn't seem to automatically work for me.

Even stranger, when I add this to `config/app.php`, the alias still doesn't work:

```
'aliases' => [
    // ...
    'Settings' => hackerESQ\Settings\Facades\Settings::class,
];
```

What works is adding this to the top of each class where I want to use your Settings: `use hackerESQ\Settings\Facades\Settings;`

But why would that be necessary?

I'm confused why your instructions wouldn't be working for me on Laravel 5.7 and am hoping you have ideas. 

Thanks!

**Comment by ryancwalsh** [comment]
I have not figured out the problem yet, but I have some extra information. Interestingly, the facade works fine from a Blade view. E.g. This works inside my `cache.blade.php` view file:

```
$settings = Settings::get();
echo json_encode($settings, JSON_PRETTY_PRINT);
```

The two places it didn't work (and needed the `use` statement) are a controller and a FeatureTest.

**Comment by hackeresq** [comment]
As mentioned in the docs, you do not need to manually register the facade in `config/app.php` on 5.4+.

When you're using [facades](https://laravel.com/docs/5.7/facades), you only need to `use Settings;` at the top of your file.  As you mention, `use hackerESQ\Settings\Facades\Settings;` will work since that's the full namespace for the Settings facade. Though, you can simply `use Settings;`, which should work since it's registered in Laravel. 

If you're still having issues, please post the full .php file and error message you're having issues with.

**Comment by ryancwalsh** [comment]
Ahh ok. Somehow I'd forgotten that [facades](https://laravel.com/docs/5.7/facades) still need _some_ kind of `use` import statement.  

So I guess the weirder question is how `$settings = Settings::get();` works in the view without any `use` statement. 

I haven't found the docs that explain how that is working, but I guess with Laravel (maybe only for 5.4+?) views automatically get access to those aliases?
